import * as React from "react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { transformSync } from "@swc/core"

export async function getStaticProps() {
  const { code } = transformSync("function Foo() { console.log('test'); return <div>test</div> }", {
    minify: false,
    jsc: {
      minify: {
        compress: {
          unused: false,
        },
        mangle: false,
      },
      parser: {
        jsx: true,
        syntax: "ecmascript",
      },
      transform: null,
      target: "es2020",
    },
  })

  return {
    revalidate: 60,
    props: {
      code
    }
  }
}

export default function Home({ code }) {
  const factory = new Function("React", `return ${code}`);
  console.log(factory)
  const Foo = factory(React)
  console.log(Foo)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Foo />
      </main>
    </div>
  )
}
